#!/bin/bash

#SBATCH -A m4304_g
#SBATCH -C gpu
#SBATCH --qos=regular
#SBATCH -J surface_forcing
#SBATCH -o surface_forcing_%j.out
#SBATCH --mail-user=emma.nuss@pnnl.gov
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH -t 06:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpu-bind=none

python /global/cfs/cdirs/m4304/enuss/model-tools/code/surface_forcing.py
